name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker asia-south1-docker.pkg.dev

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=v${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          PROJECT_ID=gen-lang-client-0485141585
          REPO=axora-backend
          IMAGE=asia-south1-docker.pkg.dev/$PROJECT_ID/$REPO/axora-backend:$IMAGE_TAG

          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy axora-backend \
            --image=asia-south1-docker.pkg.dev/gen-lang-client-0485141585/axora-backend/axora-backend:$IMAGE_TAG \
            --platform=managed \
            --region=asia-south1 \
            --allow-unauthenticated \
            --quiet
